language: node_js
cache:
  directories:
    - node_modules
  yarn: true
node_js:
  - 8
install:
  -  npm install -g firebase-tools
after_success:
  - firebase deploy - project isthereuberin - token $FIREBASE_TOKEN.
